version: "3"
services:
  app:
    build: .
    command: npm start
    ports:
    - "3000:3000"
    volumes:
      - .:/usr/app
  database:
    image: postgres:10.17
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=PA"
    ports:
     - 5441:5432
    volumes:
     - pg-data:/var/lib/postgresql/data
volumes:
  pg-data:

